[package]
name = "eventster"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.9"
thiserror = "2.0.3"
tokio = "1.41.1"
vim = { version = "0.1.0", path = "../vim" }

[profile.dev]
debug = true
opt-level = 0