[package]
name = "vim_build"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "generate"
path = "src/main.rs"

[dependencies]
serde_json = "1.0"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
indexmap = { version = "2.9", features = ["serde"] }
convert_case = "0.8"
check_keyword = "0.3"
openapi30 = { path = "../openapi30" }
log = "0.4"
phf_codegen = "0.11"
