[package]
name = "vtui"
version = "0.1.2"
edition = "2024"

[dependencies]
anyhow = "1.0"
crossterm = {  version = "0.29", features = ["event-stream"]}
futures = "0.3"
tokio = {  version = "1.44", features = ["macros"]}
ratatui = {  version = "0.30" , features = ["crossterm"]}
vim_rs = { version = "0.3", path = "../../vim_rs" }
vim_macros = { version = "0.3", path = "../../vim_macros" }
chrono = "0.4"
tui-tree-widget = "0.24"
serde_json = "1.0"
log = "0.4"
simplelog = "0.12"
indexmap = {  version = "2.9", features = ["serde"] }
thiserror = "2.0.12"
dotenvy = "0.15"
