[package]
name = "vtui"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0"
crossterm = {  version = "0.28", features = ["event-stream"]}
futures = "0.3"
tokio = {  version = "1.44", features = ["macros"]}
ratatui = {  version = "0.29" , features = ["crossterm"]}
vim_rs = { version = "0.2", path = "../../vim_rs" }
vim_macros = { version = "0.2", path = "../../vim_macros" }
chrono = "0.4.40"
