use super::vim_object_trait::VimObjectTrait;
use super::dyn_serialize;
use super::convert::CastFrom;
use super::struct_enum::StructType;
use super::structs::*;
use serde::de;
use super::vim_any::VimAny;

/// FaultsByVm is the faults generated by DRS when it tries to
/// move a VM.
pub trait ClusterDrsFaultsFaultsByVmTrait : super::data_object_trait::DataObjectTrait {
    /// The VM that DRS was trying to migrate when it generated the faults.
    /// 
    /// If this property is NULL, the fault is not associated with a particular VM.
    /// 
    /// Refers instance of *VirtualMachine*.
    fn get_vm(&self) -> &Option<ManagedObjectReference>;
    /// The faults generated by DRS when it was trying to move the given VM.
    fn get_fault(&self) -> &Vec<Box<dyn super::method_fault_trait::MethodFaultTrait>>;
}
impl<'s> serde::Serialize for dyn ClusterDrsFaultsFaultsByVmTrait + 's {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where
                S: serde::Serializer,
            {
                dyn_serialize::serialize_polymorphic(self.as_vim_object_ref(), serializer)
            }
        }
impl<'de> serde::Deserialize<'de> for Box<dyn ClusterDrsFaultsFaultsByVmTrait> {
            fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                deserializer.deserialize_map(ClusterDrsFaultsFaultsByVmVisitor)
            }
        }

struct ClusterDrsFaultsFaultsByVmVisitor;

impl<'de> de::Visitor<'de> for ClusterDrsFaultsFaultsByVmVisitor {
    type Value = Box<dyn ClusterDrsFaultsFaultsByVmTrait>;

    fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
        formatter.write_str("a valid ClusterDrsFaultsFaultsByVmTrait JSON object with a _typeName field")
    }

    fn visit_map<A>(self, mut map: A) -> Result<Self::Value, A::Error>
    where
        A: de::MapAccess<'de>,
    {
        let deserializer = de::value::MapAccessDeserializer::new(&mut map);
        let any: VimAny = de::Deserialize::deserialize(deserializer)?;
        match any {
            VimAny::Object(obj) => Ok(CastFrom::from_box(obj)
                .map_err(|_| de::Error::custom("Internal error converting to trait type"))?),
            VimAny::Value(value) => Err(de::Error::custom(format!(
                "expected object not wrapped value: {:?}",
                value))),
        }
    }
}

impl ClusterDrsFaultsFaultsByVmTrait for ClusterDrsFaultsFaultsByVm {
    fn get_vm(&self) -> &Option<ManagedObjectReference> { &self.vm }
    fn get_fault(&self) -> &Vec<Box<dyn super::method_fault_trait::MethodFaultTrait>> { &self.fault }
}
impl ClusterDrsFaultsFaultsByVmTrait for ClusterDrsFaultsFaultsByVirtualDisk {
    fn get_vm(&self) -> &Option<ManagedObjectReference> { &self.vm }
    fn get_fault(&self) -> &Vec<Box<dyn super::method_fault_trait::MethodFaultTrait>> { &self.fault }
}
impl<From: VimObjectTrait + ?Sized + 'static> CastFrom<From> for dyn ClusterDrsFaultsFaultsByVmTrait {
    fn from_ref<'a>(from: &'a From) -> Option<&'a Self> {
        let data_type = from.data_type();
        match data_type {
            StructType::ClusterDrsFaultsFaultsByVm => Some(from.as_any_ref().downcast_ref::<ClusterDrsFaultsFaultsByVm>()?),
            StructType::ClusterDrsFaultsFaultsByVirtualDisk => Some(from.as_any_ref().downcast_ref::<ClusterDrsFaultsFaultsByVirtualDisk>()?),
            _ => None,
        }
    }
    
    fn from_box(from: Box<From>) -> Result<Box<Self>, Box<dyn std::any::Any + 'static>> {
        let data_type = from.data_type();
        match data_type {
            StructType::ClusterDrsFaultsFaultsByVm => Ok(from.as_any_box().downcast::<ClusterDrsFaultsFaultsByVm>()?),
            StructType::ClusterDrsFaultsFaultsByVirtualDisk => Ok(from.as_any_box().downcast::<ClusterDrsFaultsFaultsByVirtualDisk>()?),
            _ => Err(from.as_any_box()),
        }
    }
}
