[workspace]
members = ["eventster", "mac_monitor", "vim_tests", "perf_metrics"]
resolver = "2"

[profile.release]
lto = "fat"
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
debug = false
