[workspace]
members = ["eventster", "mac_monitor", "property_collector", "perf_metrics", "environment_browser"]
resolver = "2"

[profile.release]
lto = "fat"
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
debug = false
