[package]
name = "eventster"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
env_logger = "0.11.6"
log = "0.4.26"
reqwest = "0.12.12"
thiserror = "2.0.11"
tokio = "1.43.0"
vim = { version = "0.1.0", path = "../../vim" }
utils = { version = "0.1.0", path = "../utils" }