use std::sync::Arc;
use crate::core::client::{VimClient, Result};
/// CertificateManager provides an interface for managing the SSL
/// certificates used by the server.
#[derive(Clone)]
pub struct HostCertificateManager {
    client: Arc<dyn VimClient>,
    mo_id: String,
}
impl HostCertificateManager {
    pub fn new(client: Arc<dyn VimClient>, mo_id: &str) -> Self {
        Self {
            client,
            mo_id: mo_id.to_string(),
        }
    }
    /// Requests the server to generate a certificate-signing
    /// request (CSR) for itself.
    /// 
    /// The CSR is then typically
    /// provided to a Certificate Authority to sign and issue
    /// the SSL certificate for the server. Use *HostCertificateManager.InstallServerCertificate*
    /// to install this certificate.
    /// 
    /// ***Required privileges:*** Certificate.Manage
    ///
    /// ## Parameters:
    ///
    /// ### use_ip_address_as_common_name
    /// if true, use host's
    /// management IP address as CN in the CSR;
    /// otherwise use host's FQDN.
    ///
    /// ### spec
    /// is used to generate CSR for selected
    /// certificate kind.
    /// 
    /// ***Since:*** vSphere API Release 8.0.1.0
    ///
    /// ## Returns:
    ///
    /// CSR in PEM format
    ///
    /// ## Errors:
    ///
    /// ***HostConfigFault***: if there's a problem generating the CSR.
    pub async fn generate_certificate_signing_request(&self, use_ip_address_as_common_name: bool, spec: Option<&crate::types::structs::HostCertificateManagerCertificateSpec>) -> Result<String> {
        let input = GenerateCertificateSigningRequestRequestType {use_ip_address_as_common_name, spec, };
        let path = format!("/HostCertificateManager/{moId}/GenerateCertificateSigningRequest", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        let bytes = self.client.execute_bytes(req).await?;
        let text = std::str::from_utf8(bytes.as_ref()).map_err(|e| crate::core::client::VimError::ParseError(e.to_string()))?;
        let result: String = miniserde::json::from_str(text).map_err(|_| crate::core::client::VimError::ParseError("miniserde deserialization failed".to_string()))?;
        Ok(result)
    }
    /// Requests the server to generate a certificate-signing
    /// request (CSR) for itself.
    /// 
    /// Alternative version similar to *HostCertificateManager.GenerateCertificateSigningRequest*
    /// but takes a Distinguished Name (DN) as a parameter.
    /// 
    /// ***Required privileges:*** Certificate.Manage
    ///
    /// ## Parameters:
    ///
    /// ### distinguished_name
    /// DN to be used as subject in CSR.
    ///
    /// ### spec
    /// is used to generate CSR for selected certificate kind
    /// 
    /// ***Since:*** vSphere API Release 8.0.1.0
    ///
    /// ## Returns:
    ///
    /// CSR in PEM format
    ///
    /// ## Errors:
    ///
    /// ***HostConfigFault***: if there's a problem generating the CSR.
    pub async fn generate_certificate_signing_request_by_dn(&self, distinguished_name: &str, spec: Option<&crate::types::structs::HostCertificateManagerCertificateSpec>) -> Result<String> {
        let input = GenerateCertificateSigningRequestByDnRequestType {distinguished_name, spec, };
        let path = format!("/HostCertificateManager/{moId}/GenerateCertificateSigningRequestByDn", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        let bytes = self.client.execute_bytes(req).await?;
        let text = std::str::from_utf8(bytes.as_ref()).map_err(|e| crate::core::client::VimError::ParseError(e.to_string()))?;
        let result: String = miniserde::json::from_str(text).map_err(|_| crate::core::client::VimError::ParseError("miniserde deserialization failed".to_string()))?;
        Ok(result)
    }
    /// Installs a given SSL certificate on the server.
    /// 
    /// The private key must have been previously generated by *HostCertificateManager.GenerateCertificateSigningRequest* or provided
    /// by *HostCertificateManager.ProvisionServerPrivateKey*.
    /// 
    /// ***Required privileges:*** Certificate.Manage
    ///
    /// ## Parameters:
    ///
    /// ### cert
    /// SSL certificate in PEM format
    ///
    /// ## Errors:
    ///
    /// ***HostConfigFault***: if there's a problem with the input certificate,
    /// or the certificate and key don't match.
    pub async fn install_server_certificate(&self, cert: &str) -> Result<()> {
        let input = InstallServerCertificateRequestType {cert, };
        let path = format!("/HostCertificateManager/{moId}/InstallServerCertificate", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        self.client.execute_void(req).await
    }
    /// Fetches the SSL CRLs of Certificate Authorities that are trusted.
    /// 
    /// ***Required privileges:*** Certificate.Manage
    ///
    /// ## Returns:
    ///
    /// SSL CRLs of trusted CAs in PEM format
    ///
    /// ## Errors:
    ///
    /// ***HostConfigFault***: if there's a problem with the certificate store.
    pub async fn list_ca_certificate_revocation_lists(&self) -> Result<Option<Vec<String>>> {
        let path = format!("/HostCertificateManager/{moId}/ListCACertificateRevocationLists", moId = &self.mo_id);
        let req = self.client.post_bare(&path);
        let bytes_opt = self.client.execute_option_bytes(req).await?;
        match bytes_opt {
            Some(bytes) => {
                let text = std::str::from_utf8(bytes.as_ref()).map_err(|e| crate::core::client::VimError::ParseError(e.to_string()))?;
                Ok(Some(miniserde::json::from_str::<Vec<String>>(text).map_err(|_| crate::core::client::VimError::ParseError("miniserde deserialization failed".to_string()))?))
            }
            None => Ok(None),
        }
    }
    /// Fetches the SSL certificates of Certificate Authorities
    /// that are trusted.
    /// 
    /// ***Required privileges:*** Certificate.Manage
    ///
    /// ## Returns:
    ///
    /// SSL certificates of trusted CAs in PEM format
    ///
    /// ## Errors:
    ///
    /// ***HostConfigFault***: if there's a problem with the certificate store.
    pub async fn list_ca_certificates(&self) -> Result<Option<Vec<String>>> {
        let path = format!("/HostCertificateManager/{moId}/ListCACertificates", moId = &self.mo_id);
        let req = self.client.post_bare(&path);
        let bytes_opt = self.client.execute_option_bytes(req).await?;
        match bytes_opt {
            Some(bytes) => {
                let text = std::str::from_utf8(bytes.as_ref()).map_err(|e| crate::core::client::VimError::ParseError(e.to_string()))?;
                Ok(Some(miniserde::json::from_str::<Vec<String>>(text).map_err(|_| crate::core::client::VimError::ParseError("miniserde deserialization failed".to_string()))?))
            }
            None => Ok(None),
        }
    }
    /// Instructs the host services affected by SSL credential changes
    /// by *HostCertificateManager.InstallServerCertificate*
    /// or *HostCertificateManager.ReplaceCACertificatesAndCRLs*
    /// to take into account said changes now.
    /// 
    /// Please note, that
    /// old SSL connections typically survive the transition and continue using
    /// old SSL credentials. New SSL connections will use the new SSL credentials.
    /// 
    /// ***Required privileges:*** Certificate.Manage
    ///
    /// ## Parameters:
    ///
    /// ### services
    /// list of services that need to be notified and no
    /// other service would be notified. if not provided all supported
    /// services would be notified.
    /// 
    /// ***Since:*** vSphere API Release 8.0.1.0
    pub async fn notify_affected_services(&self, services: Option<&[String]>) -> Result<()> {
        let input = NotifyAffectedServicesRequestType {services, };
        let path = format!("/HostCertificateManager/{moId}/NotifyAffectedServices", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        self.client.execute_void(req).await
    }
    /// Provisions a given SSL private key on the server for use with a subsequent
    /// SSL certificate installation.
    /// 
    /// The recommended way to update the server private key is via *HostCertificateManager.GenerateCertificateSigningRequest*, which
    /// ensures that the key never leaves the host.
    /// 
    /// The current method is intended for use only in environments that
    /// have special requirements on how their private keys are generated.
    /// 
    /// ***Since:*** vSphere API Release 8.0.3.0
    /// 
    /// ***Required privileges:*** Certificate.Manage
    ///
    /// ## Parameters:
    ///
    /// ### key
    /// SSL private key in PEM format
    ///
    /// ## Errors:
    ///
    /// ***HostConfigFault***: if there's a problem with the input key.
    pub async fn provision_server_private_key(&self, key: &str) -> Result<()> {
        let input = ProvisionServerPrivateKeyRequestType {key, };
        let path = format!("/HostCertificateManager/{moId}/ProvisionServerPrivateKey", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        self.client.execute_void(req).await
    }
    /// Replaces the trusted Certificate Authority (CA)
    /// certificates and Certification Revocation List (CRL)
    /// used by the server with the provided values.
    /// 
    /// These determine whether the server can verify
    /// the identity of an external entity.
    /// 
    /// ***Required privileges:*** Certificate.Manage
    ///
    /// ## Parameters:
    ///
    /// ### ca_cert
    /// List of SSL certificates, in PEM format,
    /// of all CAs that should be trusted
    ///
    /// ### ca_crl
    /// List of SSL CRLs, in PEM format,
    /// issued by trusted CAs from the above list
    ///
    /// ## Errors:
    ///
    /// ***HostConfigFault***: if there's a problem with the input certificates
    /// or CRLs.
    pub async fn replace_ca_certificates_and_cr_ls(&self, ca_cert: &[String], ca_crl: Option<&[String]>) -> Result<()> {
        let input = ReplaceCaCertificatesAndCrLsRequestType {ca_cert, ca_crl, };
        let path = format!("/HostCertificateManager/{moId}/ReplaceCACertificatesAndCRLs", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        self.client.execute_void(req).await
    }
    /// the CertificateInfos of all known Certificates on
    /// the host
    /// 
    /// ***Since:*** vSphere API Release 8.0.1.0
    /// 
    /// ***Required privileges:*** Certificate.Manage
    pub async fn retrieve_certificate_info_list(&self) -> Result<Option<Vec<crate::types::structs::HostCertificateManagerCertificateInfo>>> {
        let path = format!("/HostCertificateManager/{moId}/RetrieveCertificateInfoList", moId = &self.mo_id);
        let req = self.client.post_bare(&path);
        let bytes_opt = self.client.execute_option_bytes(req).await?;
        match bytes_opt {
            Some(bytes) => {
                let text = std::str::from_utf8(bytes.as_ref()).map_err(|e| crate::core::client::VimError::ParseError(e.to_string()))?;
                Ok(Some(miniserde::json::from_str::<Vec<crate::types::structs::HostCertificateManagerCertificateInfo>>(text).map_err(|_| crate::core::client::VimError::ParseError("miniserde deserialization failed".to_string()))?))
            }
            None => Ok(None),
        }
    }
    /// the CertificateInfo of the Host Certificate.
    /// 
    /// ***Required privileges:*** Certificate.Manage
    pub async fn certificate_info(&self) -> Result<crate::types::structs::HostCertificateManagerCertificateInfo> {
        let path = format!("/HostCertificateManager/{moId}/certificateInfo", moId = &self.mo_id);
        let req = self.client.get_request(&path);
        let bytes = self.client.execute_bytes(req).await?;
        let text = std::str::from_utf8(bytes.as_ref()).map_err(|e| crate::core::client::VimError::ParseError(e.to_string()))?;
        let result: crate::types::structs::HostCertificateManagerCertificateInfo = miniserde::json::from_str(text).map_err(|_| crate::core::client::VimError::ParseError("miniserde deserialization failed".to_string()))?;
        Ok(result)
    }
}
struct GenerateCertificateSigningRequestRequestType<'a> {
    use_ip_address_as_common_name: bool,
    spec: Option<&'a crate::types::structs::HostCertificateManagerCertificateSpec>,
}

impl<'a> miniserde::Serialize for GenerateCertificateSigningRequestRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(GenerateCertificateSigningRequestRequestTypeSer { data: self, seq: 0 }))
    }
}

struct GenerateCertificateSigningRequestRequestTypeSer<'b, 'a> {
    data: &'b GenerateCertificateSigningRequestRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for GenerateCertificateSigningRequestRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        loop {
            let seq = self.seq;
            self.seq += 1;
            match seq {
                0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"GenerateCertificateSigningRequestRequestType")),
                1 => return Some((std::borrow::Cow::Borrowed("useIpAddressAsCommonName"), &self.data.use_ip_address_as_common_name as &dyn miniserde::Serialize)),
                2 => {
                    let Some(ref val) = self.data.spec else { continue; };
                    return Some((std::borrow::Cow::Borrowed("spec"), val as &dyn miniserde::Serialize));
                }
                _ => return None,
            }
        }
    }
}
struct GenerateCertificateSigningRequestByDnRequestType<'a> {
    distinguished_name: &'a str,
    spec: Option<&'a crate::types::structs::HostCertificateManagerCertificateSpec>,
}

impl<'a> miniserde::Serialize for GenerateCertificateSigningRequestByDnRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(GenerateCertificateSigningRequestByDnRequestTypeSer { data: self, seq: 0 }))
    }
}

struct GenerateCertificateSigningRequestByDnRequestTypeSer<'b, 'a> {
    data: &'b GenerateCertificateSigningRequestByDnRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for GenerateCertificateSigningRequestByDnRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        loop {
            let seq = self.seq;
            self.seq += 1;
            match seq {
                0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"GenerateCertificateSigningRequestByDnRequestType")),
                1 => return Some((std::borrow::Cow::Borrowed("distinguishedName"), &self.data.distinguished_name as &dyn miniserde::Serialize)),
                2 => {
                    let Some(ref val) = self.data.spec else { continue; };
                    return Some((std::borrow::Cow::Borrowed("spec"), val as &dyn miniserde::Serialize));
                }
                _ => return None,
            }
        }
    }
}
struct InstallServerCertificateRequestType<'a> {
    cert: &'a str,
}

impl<'a> miniserde::Serialize for InstallServerCertificateRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(InstallServerCertificateRequestTypeSer { data: self, seq: 0 }))
    }
}

struct InstallServerCertificateRequestTypeSer<'b, 'a> {
    data: &'b InstallServerCertificateRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for InstallServerCertificateRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        let seq = self.seq;
        self.seq += 1;
        match seq {
            0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"InstallServerCertificateRequestType")),
            1 => return Some((std::borrow::Cow::Borrowed("cert"), &self.data.cert as &dyn miniserde::Serialize)),
            _ => return None,
        }
    }
}
struct NotifyAffectedServicesRequestType<'a> {
    services: Option<&'a [String]>,
}

impl<'a> miniserde::Serialize for NotifyAffectedServicesRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(NotifyAffectedServicesRequestTypeSer { data: self, seq: 0 }))
    }
}

struct NotifyAffectedServicesRequestTypeSer<'b, 'a> {
    data: &'b NotifyAffectedServicesRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for NotifyAffectedServicesRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        loop {
            let seq = self.seq;
            self.seq += 1;
            match seq {
                0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"NotifyAffectedServicesRequestType")),
                1 => {
                    let Some(ref val) = self.data.services else { continue; };
                    return Some((std::borrow::Cow::Borrowed("services"), val as &dyn miniserde::Serialize));
                }
                _ => return None,
            }
        }
    }
}
struct ProvisionServerPrivateKeyRequestType<'a> {
    key: &'a str,
}

impl<'a> miniserde::Serialize for ProvisionServerPrivateKeyRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(ProvisionServerPrivateKeyRequestTypeSer { data: self, seq: 0 }))
    }
}

struct ProvisionServerPrivateKeyRequestTypeSer<'b, 'a> {
    data: &'b ProvisionServerPrivateKeyRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for ProvisionServerPrivateKeyRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        let seq = self.seq;
        self.seq += 1;
        match seq {
            0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"ProvisionServerPrivateKeyRequestType")),
            1 => return Some((std::borrow::Cow::Borrowed("key"), &self.data.key as &dyn miniserde::Serialize)),
            _ => return None,
        }
    }
}
struct ReplaceCaCertificatesAndCrLsRequestType<'a> {
    ca_cert: &'a [String],
    ca_crl: Option<&'a [String]>,
}

impl<'a> miniserde::Serialize for ReplaceCaCertificatesAndCrLsRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(ReplaceCaCertificatesAndCrLsRequestTypeSer { data: self, seq: 0 }))
    }
}

struct ReplaceCaCertificatesAndCrLsRequestTypeSer<'b, 'a> {
    data: &'b ReplaceCaCertificatesAndCrLsRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for ReplaceCaCertificatesAndCrLsRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        loop {
            let seq = self.seq;
            self.seq += 1;
            match seq {
                0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"ReplaceCACertificatesAndCRLsRequestType")),
                1 => return Some((std::borrow::Cow::Borrowed("caCert"), &self.data.ca_cert as &dyn miniserde::Serialize)),
                2 => {
                    let Some(ref val) = self.data.ca_crl else { continue; };
                    return Some((std::borrow::Cow::Borrowed("caCrl"), val as &dyn miniserde::Serialize));
                }
                _ => return None,
            }
        }
    }
}
