use std::sync::Arc;
use crate::core::client::{VimClient, Result};
/// Singleton Managed Object used to manage IP Pools.
/// 
/// IP Pools are used to allocate IPv4 and IPv6 addresses to vApps.
#[derive(Clone)]
pub struct IpPoolManager {
    client: Arc<dyn VimClient>,
    mo_id: String,
}
impl IpPoolManager {
    pub fn new(client: Arc<dyn VimClient>, mo_id: &str) -> Self {
        Self {
            client,
            mo_id: mo_id.to_string(),
        }
    }
    /// Allocates an IPv4 address from an IP pool.
    /// 
    /// Allocated IP addresses are reserved in the IP pool until released by
    /// calling *IpPoolManager.ReleaseIpAllocation*, or until the IP pool is configured to
    /// have an IP range that does not contain the IP address, or until the IP
    /// pool is destroyed.
    /// 
    /// The caller must be a vCenter extension. Refer to *ExtensionManager*
    /// for details on vCenter extensions.
    /// 
    /// The caller specifies a per extension unique allocation ID. Calling this
    /// function twice with the same allocation ID for the same pool yields the
    /// same IP address. This makes it possible to do idempotent allocations.
    ///
    /// ## Parameters:
    ///
    /// ### dc
    /// The datacenter on which to find the pool
    /// 
    /// Refers instance of *Datacenter*.
    ///
    /// ### pool_id
    /// The unique ID of the pool
    ///
    /// ### allocation_id
    /// The unique ID for this allocation
    ///
    /// ## Returns:
    ///
    /// An IPv4 address if the pool has an available IPv4 address in its
    /// address ranges, otherwise the empty string.
    pub async fn allocate_ipv_4_address(&self, dc: &crate::types::structs::ManagedObjectReference, pool_id: i32, allocation_id: &str) -> Result<String> {
        let input = AllocateIpv4AddressRequestType {dc, pool_id, allocation_id, };
        let path = format!("/IpPoolManager/{moId}/AllocateIpv4Address", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        let bytes = self.client.execute_bytes(req).await?;
        let text = std::str::from_utf8(bytes.as_ref()).map_err(|e| crate::core::client::VimError::ParseError(e.to_string()))?;
        let result: String = miniserde::json::from_str(text).map_err(|_| crate::core::client::VimError::ParseError("miniserde deserialization failed".to_string()))?;
        Ok(result)
    }
    /// Allocates an IPv6 address from an IP pool.
    /// 
    /// Allocated IP addresses are reserved in the IP pool until released by
    /// calling *IpPoolManager.ReleaseIpAllocation*, or until the IP pool is configured to
    /// have an IP range that does not contain the IP address, or until the IP
    /// pool is destroyed.
    /// 
    /// The caller must be a vCenter extension. Refer to *ExtensionManager*
    /// for details on vCenter extensions.
    /// 
    /// The caller specifies a per extension unique allocation ID. Calling this
    /// function twice with the same allocation ID for the same pool yields the
    /// same IP address. This makes it possible to do idempotent allocations.
    ///
    /// ## Parameters:
    ///
    /// ### dc
    /// The datacenter on which to find the pool
    /// 
    /// Refers instance of *Datacenter*.
    ///
    /// ### pool_id
    /// The unique ID of the pool
    ///
    /// ### allocation_id
    /// The unique ID for this allocation
    ///
    /// ## Returns:
    ///
    /// An IPv6 address if the pool has an available IPv6 address in its
    /// address ranges, otherwise the empty string.
    pub async fn allocate_ipv_6_address(&self, dc: &crate::types::structs::ManagedObjectReference, pool_id: i32, allocation_id: &str) -> Result<String> {
        let input = AllocateIpv6AddressRequestType {dc, pool_id, allocation_id, };
        let path = format!("/IpPoolManager/{moId}/AllocateIpv6Address", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        let bytes = self.client.execute_bytes(req).await?;
        let text = std::str::from_utf8(bytes.as_ref()).map_err(|e| crate::core::client::VimError::ParseError(e.to_string()))?;
        let result: String = miniserde::json::from_str(text).map_err(|_| crate::core::client::VimError::ParseError("miniserde deserialization failed".to_string()))?;
        Ok(result)
    }
    /// Create a new IP pool.
    /// 
    /// The name field must be defined, all other fields are optional. If unset,
    /// they will be given default values.
    /// 
    /// The ID for the pool is generated by the server and should not be defined on the
    /// pool object passed to this method.
    ///
    /// ## Parameters:
    ///
    /// ### dc
    /// The datacenter on which to create the pool.
    /// 
    /// ***Required privileges:*** Datacenter.IpPoolConfig
    /// 
    /// Refers instance of *Datacenter*.
    ///
    /// ### pool
    /// The IP pool to create on the server
    ///
    /// ## Returns:
    ///
    /// The generated ID for the pool
    pub async fn create_ip_pool(&self, dc: &crate::types::structs::ManagedObjectReference, pool: &crate::types::structs::IpPool) -> Result<i32> {
        let input = CreateIpPoolRequestType {dc, pool, };
        let path = format!("/IpPoolManager/{moId}/CreateIpPool", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        let bytes = self.client.execute_bytes(req).await?;
        let text = std::str::from_utf8(bytes.as_ref()).map_err(|e| crate::core::client::VimError::ParseError(e.to_string()))?;
        let result: i32 = miniserde::json::from_str(text).map_err(|_| crate::core::client::VimError::ParseError("miniserde deserialization failed".to_string()))?;
        Ok(result)
    }
    /// Destroys an IP pool on the given datacenter.
    /// 
    /// Looks up the pool on the datacenter by ID and deletes it. If the pool is in use,
    /// the method throws InvalidState unless the force flag is true.
    ///
    /// ## Parameters:
    ///
    /// ### dc
    /// The datacenter on which to find the pool
    /// 
    /// ***Required privileges:*** Datacenter.IpPoolConfig
    /// 
    /// Refers instance of *Datacenter*.
    ///
    /// ### id
    /// The unique ID of the pool
    ///
    /// ### force
    /// If true, the pool will be destroyed even if it is in use
    ///
    /// ## Errors:
    ///
    /// ***InvalidState***: if the pool is in use and the force flag is false
    pub async fn destroy_ip_pool(&self, dc: &crate::types::structs::ManagedObjectReference, id: i32, force: bool) -> Result<()> {
        let input = DestroyIpPoolRequestType {dc, id, force, };
        let path = format!("/IpPoolManager/{moId}/DestroyIpPool", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        self.client.execute_void(req).await
    }
    /// Query IP allocations by IP pool and extension key.
    ///
    /// ## Parameters:
    ///
    /// ### dc
    /// The datacenter on which to find the pool
    /// 
    /// ***Required privileges:*** Datacenter.IpPoolQueryAllocations
    /// 
    /// Refers instance of *Datacenter*.
    ///
    /// ### pool_id
    /// The unique ID of the pool
    ///
    /// ### extension_key
    /// The key of the extension
    ///
    /// ## Returns:
    ///
    /// The resulting list of *IpPoolManagerIpAllocation*.
    pub async fn query_ip_allocations(&self, dc: &crate::types::structs::ManagedObjectReference, pool_id: i32, extension_key: &str) -> Result<Vec<crate::types::structs::IpPoolManagerIpAllocation>> {
        let input = QueryIpAllocationsRequestType {dc, pool_id, extension_key, };
        let path = format!("/IpPoolManager/{moId}/QueryIPAllocations", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        let bytes = self.client.execute_bytes(req).await?;
        let text = std::str::from_utf8(bytes.as_ref()).map_err(|e| crate::core::client::VimError::ParseError(e.to_string()))?;
        let result: Vec<crate::types::structs::IpPoolManagerIpAllocation> = miniserde::json::from_str(text).map_err(|_| crate::core::client::VimError::ParseError("miniserde deserialization failed".to_string()))?;
        Ok(result)
    }
    /// Return the list of IP pools for a datacenter.
    ///
    /// ## Parameters:
    ///
    /// ### dc
    /// The datacenter for which to look up the IP pools.
    /// 
    /// ***Required privileges:*** System.Read
    /// 
    /// Refers instance of *Datacenter*.
    ///
    /// ## Returns:
    ///
    /// The resulting list of pools.
    pub async fn query_ip_pools(&self, dc: &crate::types::structs::ManagedObjectReference) -> Result<Option<Vec<crate::types::structs::IpPool>>> {
        let input = QueryIpPoolsRequestType {dc, };
        let path = format!("/IpPoolManager/{moId}/QueryIpPools", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        let bytes_opt = self.client.execute_option_bytes(req).await?;
        match bytes_opt {
            Some(bytes) => {
                let text = std::str::from_utf8(bytes.as_ref()).map_err(|e| crate::core::client::VimError::ParseError(e.to_string()))?;
                Ok(Some(miniserde::json::from_str::<Vec<crate::types::structs::IpPool>>(text).map_err(|_| crate::core::client::VimError::ParseError("miniserde deserialization failed".to_string()))?))
            }
            None => Ok(None),
        }
    }
    /// Releases an IP allocation back to it's IP pool.
    /// 
    /// Attempting to release an IP allocation that is not allocated from the
    /// specified IP pool with the specified allocation ID silently fails. This
    /// makes it possible to release IP allocations idempotently.
    /// 
    /// All IP addresses allocated by an extension are automatically released
    /// if the extension is unregistered from vCenter.
    ///
    /// ## Parameters:
    ///
    /// ### dc
    /// The datacenter on which to find the pool
    /// 
    /// ***Required privileges:*** Datacenter.IpPoolReleaseIp
    /// 
    /// Refers instance of *Datacenter*.
    ///
    /// ### pool_id
    /// The unique ID of the pool
    ///
    /// ### allocation_id
    /// The unique ID for this allocation
    pub async fn release_ip_allocation(&self, dc: &crate::types::structs::ManagedObjectReference, pool_id: i32, allocation_id: &str) -> Result<()> {
        let input = ReleaseIpAllocationRequestType {dc, pool_id, allocation_id, };
        let path = format!("/IpPoolManager/{moId}/ReleaseIpAllocation", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        self.client.execute_void(req).await
    }
    /// Update an IP pool on a datacenter.
    /// 
    /// The pool to update is looked up from the value of the id field.
    /// 
    /// All fields in the pool except the id are optional. Only defined values are stored
    /// on the server.
    ///
    /// ## Parameters:
    ///
    /// ### dc
    /// The datacenter on which to look up the pool.
    /// 
    /// ***Required privileges:*** Datacenter.IpPoolConfig
    /// 
    /// Refers instance of *Datacenter*.
    ///
    /// ### pool
    /// The IP pool to update on the server
    pub async fn update_ip_pool(&self, dc: &crate::types::structs::ManagedObjectReference, pool: &crate::types::structs::IpPool) -> Result<()> {
        let input = UpdateIpPoolRequestType {dc, pool, };
        let path = format!("/IpPoolManager/{moId}/UpdateIpPool", moId = &self.mo_id);
        let req = self.client.post_json(&path, &input);
        self.client.execute_void(req).await
    }
}
struct AllocateIpv4AddressRequestType<'a> {
    dc: &'a crate::types::structs::ManagedObjectReference,
    pool_id: i32,
    allocation_id: &'a str,
}

impl<'a> miniserde::Serialize for AllocateIpv4AddressRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(AllocateIpv4AddressRequestTypeSer { data: self, seq: 0 }))
    }
}

struct AllocateIpv4AddressRequestTypeSer<'b, 'a> {
    data: &'b AllocateIpv4AddressRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for AllocateIpv4AddressRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        let seq = self.seq;
        self.seq += 1;
        match seq {
            0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"AllocateIpv4AddressRequestType")),
            1 => return Some((std::borrow::Cow::Borrowed("dc"), &self.data.dc as &dyn miniserde::Serialize)),
            2 => return Some((std::borrow::Cow::Borrowed("poolId"), &self.data.pool_id as &dyn miniserde::Serialize)),
            3 => return Some((std::borrow::Cow::Borrowed("allocationId"), &self.data.allocation_id as &dyn miniserde::Serialize)),
            _ => return None,
        }
    }
}
struct AllocateIpv6AddressRequestType<'a> {
    dc: &'a crate::types::structs::ManagedObjectReference,
    pool_id: i32,
    allocation_id: &'a str,
}

impl<'a> miniserde::Serialize for AllocateIpv6AddressRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(AllocateIpv6AddressRequestTypeSer { data: self, seq: 0 }))
    }
}

struct AllocateIpv6AddressRequestTypeSer<'b, 'a> {
    data: &'b AllocateIpv6AddressRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for AllocateIpv6AddressRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        let seq = self.seq;
        self.seq += 1;
        match seq {
            0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"AllocateIpv6AddressRequestType")),
            1 => return Some((std::borrow::Cow::Borrowed("dc"), &self.data.dc as &dyn miniserde::Serialize)),
            2 => return Some((std::borrow::Cow::Borrowed("poolId"), &self.data.pool_id as &dyn miniserde::Serialize)),
            3 => return Some((std::borrow::Cow::Borrowed("allocationId"), &self.data.allocation_id as &dyn miniserde::Serialize)),
            _ => return None,
        }
    }
}
struct CreateIpPoolRequestType<'a> {
    dc: &'a crate::types::structs::ManagedObjectReference,
    pool: &'a crate::types::structs::IpPool,
}

impl<'a> miniserde::Serialize for CreateIpPoolRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(CreateIpPoolRequestTypeSer { data: self, seq: 0 }))
    }
}

struct CreateIpPoolRequestTypeSer<'b, 'a> {
    data: &'b CreateIpPoolRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for CreateIpPoolRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        let seq = self.seq;
        self.seq += 1;
        match seq {
            0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"CreateIpPoolRequestType")),
            1 => return Some((std::borrow::Cow::Borrowed("dc"), &self.data.dc as &dyn miniserde::Serialize)),
            2 => return Some((std::borrow::Cow::Borrowed("pool"), &self.data.pool as &dyn miniserde::Serialize)),
            _ => return None,
        }
    }
}
struct DestroyIpPoolRequestType<'a> {
    dc: &'a crate::types::structs::ManagedObjectReference,
    id: i32,
    force: bool,
}

impl<'a> miniserde::Serialize for DestroyIpPoolRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(DestroyIpPoolRequestTypeSer { data: self, seq: 0 }))
    }
}

struct DestroyIpPoolRequestTypeSer<'b, 'a> {
    data: &'b DestroyIpPoolRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for DestroyIpPoolRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        let seq = self.seq;
        self.seq += 1;
        match seq {
            0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"DestroyIpPoolRequestType")),
            1 => return Some((std::borrow::Cow::Borrowed("dc"), &self.data.dc as &dyn miniserde::Serialize)),
            2 => return Some((std::borrow::Cow::Borrowed("id"), &self.data.id as &dyn miniserde::Serialize)),
            3 => return Some((std::borrow::Cow::Borrowed("force"), &self.data.force as &dyn miniserde::Serialize)),
            _ => return None,
        }
    }
}
struct QueryIpAllocationsRequestType<'a> {
    dc: &'a crate::types::structs::ManagedObjectReference,
    pool_id: i32,
    extension_key: &'a str,
}

impl<'a> miniserde::Serialize for QueryIpAllocationsRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(QueryIpAllocationsRequestTypeSer { data: self, seq: 0 }))
    }
}

struct QueryIpAllocationsRequestTypeSer<'b, 'a> {
    data: &'b QueryIpAllocationsRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for QueryIpAllocationsRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        let seq = self.seq;
        self.seq += 1;
        match seq {
            0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"QueryIPAllocationsRequestType")),
            1 => return Some((std::borrow::Cow::Borrowed("dc"), &self.data.dc as &dyn miniserde::Serialize)),
            2 => return Some((std::borrow::Cow::Borrowed("poolId"), &self.data.pool_id as &dyn miniserde::Serialize)),
            3 => return Some((std::borrow::Cow::Borrowed("extensionKey"), &self.data.extension_key as &dyn miniserde::Serialize)),
            _ => return None,
        }
    }
}
struct QueryIpPoolsRequestType<'a> {
    dc: &'a crate::types::structs::ManagedObjectReference,
}

impl<'a> miniserde::Serialize for QueryIpPoolsRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(QueryIpPoolsRequestTypeSer { data: self, seq: 0 }))
    }
}

struct QueryIpPoolsRequestTypeSer<'b, 'a> {
    data: &'b QueryIpPoolsRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for QueryIpPoolsRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        let seq = self.seq;
        self.seq += 1;
        match seq {
            0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"QueryIpPoolsRequestType")),
            1 => return Some((std::borrow::Cow::Borrowed("dc"), &self.data.dc as &dyn miniserde::Serialize)),
            _ => return None,
        }
    }
}
struct ReleaseIpAllocationRequestType<'a> {
    dc: &'a crate::types::structs::ManagedObjectReference,
    pool_id: i32,
    allocation_id: &'a str,
}

impl<'a> miniserde::Serialize for ReleaseIpAllocationRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(ReleaseIpAllocationRequestTypeSer { data: self, seq: 0 }))
    }
}

struct ReleaseIpAllocationRequestTypeSer<'b, 'a> {
    data: &'b ReleaseIpAllocationRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for ReleaseIpAllocationRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        let seq = self.seq;
        self.seq += 1;
        match seq {
            0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"ReleaseIpAllocationRequestType")),
            1 => return Some((std::borrow::Cow::Borrowed("dc"), &self.data.dc as &dyn miniserde::Serialize)),
            2 => return Some((std::borrow::Cow::Borrowed("poolId"), &self.data.pool_id as &dyn miniserde::Serialize)),
            3 => return Some((std::borrow::Cow::Borrowed("allocationId"), &self.data.allocation_id as &dyn miniserde::Serialize)),
            _ => return None,
        }
    }
}
struct UpdateIpPoolRequestType<'a> {
    dc: &'a crate::types::structs::ManagedObjectReference,
    pool: &'a crate::types::structs::IpPool,
}

impl<'a> miniserde::Serialize for UpdateIpPoolRequestType<'a> {
    fn begin(&self) -> miniserde::ser::Fragment<'_> {
        miniserde::ser::Fragment::Map(Box::new(UpdateIpPoolRequestTypeSer { data: self, seq: 0 }))
    }
}

struct UpdateIpPoolRequestTypeSer<'b, 'a> {
    data: &'b UpdateIpPoolRequestType<'a>,
    seq: usize,
}

impl miniserde::ser::Map for UpdateIpPoolRequestTypeSer<'_, '_> {
    fn next(&mut self) -> Option<(std::borrow::Cow<'_, str>, &dyn miniserde::Serialize)> {
        let seq = self.seq;
        self.seq += 1;
        match seq {
            0 => return Some((std::borrow::Cow::Borrowed("_typeName"), &"UpdateIpPoolRequestType")),
            1 => return Some((std::borrow::Cow::Borrowed("dc"), &self.data.dc as &dyn miniserde::Serialize)),
            2 => return Some((std::borrow::Cow::Borrowed("pool"), &self.data.pool as &dyn miniserde::Serialize)),
            _ => return None,
        }
    }
}
