[package]
name = "perf_metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
tokio = "1.41.1"
vim = { version = "0.1.0", path = "../../vim" }
utils= { version = "0.1.0", path = "../utils" }
