[package]
name = "perf_metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
env_logger = "0.11.5"
log = "0.4.22"
tokio = {  version = "1.43.0", features = ["macros"]}
vim_rs = { version = "0.1.0", path = "../../vim_rs" }
