[package]
name = "vim_rs"
version = "0.4.3"
edition = "2021"
authors = ["Kiril Karaatanasov <karaatanasov@gmail.com>"]
license = "Apache-2.0"
description = "Rust Bindings for the VMware by Broadcom vCenter VI JSON API"
readme = "../README.md"
repository = "https://github.com/noclue/vim_rs"
homepage = "https://github.com/noclue/vim_rs"
documentation = "https://docs.rs/vim_rs"
keywords = ["vi-json", "vim", "bindings", "vcenter", "vmware"]
categories = ["api-bindings", "network-programming"]
exclude = ["target/*", "**/*.rs.bk"]

[features]
defaults = []
xml = ["dep:quick-xml", "reqwest/cookies"]

[dependencies]
base64 = "0.22"
bytes = "1"
env_logger = "0.11"
indexmap = "2.9"
log = "0.4"
miniserde = "0.1"
quick-xml = { version = "0.39", optional = true }
reqwest = { version = "0.12" }
thiserror = "2.0"
tokio = { version = "1.44", features = ["rt-multi-thread", "macros", "sync"] }
vim_macros = { version = "0.4.3", path = "../vim_macros" }
phf = "0.13"

[build-dependencies]
rustc_version = "0.4"

[lib]
doctest = false

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "miniserde_bench"
harness = false
