[package]
name = "openapi30"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
indexmap = { version = "2.2.6", features = ["serde"] }
thiserror = "1.0.61"
