[package]
name = "openapi30"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
indexmap = { version = "2.7.1", features = ["serde"] }
thiserror = "2.0.11"
