[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
crossterm = "0.28.1"
ratatui = "0.29.0"
tokio = {  version = "1.43.0", features = ["macros"]}
vim_rs = { version = "0.1.0", path = "../../vim_rs" }
